module.exports = {
    semi: false,
    indent: true,
    printWidth: 100,
    singleQuote: true,
    endOfLine: 'lf',
    tabWidth: 4,
    jsxBracketSameLine: true,
    trailingComma: 'es5',
    bracketSpacing: true,
    bracketLine: true,
    vueIndentScriptAndStyle: true,
    arrowParens: 'avoid',
    eslintIntegration: true,
    plugins: [require('prettier-plugin-tailwindcss')],
}
