module.exports = {
  semi: false,
  indent: true,
  singleQuote: true,
  endOfLine: 'lf',
  tabWidth: 2,
  jsxBracketSameLine: true,
  trailingComma: 'es5',
  bracketSpacing: true,
  bracketLine: true,
  vueIndentScriptAndStyle: true,
  arrowParens: 'avoid',
  eslintIntegration: true,
  plugins: [require('prettier-plugin-tailwindcss')],
}
